### ISSUE TITLE
Missing info from GUI

### ISSUE THREAD

**Issue by Luccio96** [bnhf/openvpn-admin-plus#54]
After running the container successfully I see no connected clients (I'm connected), no certificates and some errors.
This is my stack:

```yml
version: '3'
services:
  gui:
    image: bnhf/openvpn-admin-plus:latest
    container_name: openvpn-gui-tap
    environment:
    - OPENVPN_ADMIN_USERNAME=...
    - OPENVPN_ADMIN_PASSWORD=...
    - COUNTRY=IT
    - PROVINCE=CO
    - CITY=...
    - ORG=team
    - EMAIL=...
    - OU=it
    - PIVPN_SERVER=server_5WvzCbfmkb2jPw63
    - PIVPN_CONF=server.conf
    - TZ=EU/Rome
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - /etc/openvpn:/etc/openvpn
     - ./openvpn-data/db:/opt/openvpn-gui-tap/db`
```
   
![Senza titolo](https://user-images.githubusercontent.com/41821623/232690571-d19af543-3a54-4905-bafa-9bcc78d64b70.png)
